### ISSUE TITLE
QMK Firmware

### ISSUE THREAD

**Issue by geoah** [peej/for-split-keyboard#1]
Hey @peej, thanks for open sourcing these designs. :)

I was wondering what firmware you are running for the two versions (split/non-split). The readme mentions QMK but couldn't find an existing firmware there.

Thank you very much in advance.

**Comment by peej** [comment]
Hi. I thought that I had linked the firmware from my QMK fork but I seem to never have pushed it.

I've added it here: https://github.com/peej/qmk_firmware/tree/for-split

It's untested, and there is a constant `IS_SPLIT` in the config.h which switches the setup between the split and unsplit configurations.

**Comment by geoah** [comment]
@peej thank you very much :D
